### ISSUE TITLE
16:10 No longer works as of v2.3.0

### ISSUE THREAD

**Issue by sslovelady** [xzyxzy/switch-patches#1]
First off, thanks for your work.

Would you be willing to update the patch to support 2.3.0? 
Although there will most likely be a new version on July 12th when the next booster pack releases. May be better to wait for that version.

**Comment by xzyxzy** [comment]
Drop a comment here again when update will drop and I'll try my best on updating it.

**Comment by xzyxzy** [comment]
Someone was faster than me :)

https://pixeldrain.com/u/PWWqXwLn
