### ISSUE TITLE
Updating Mario Kart 8 Deluxe (16:10 patch) for v3.0.1?

### ISSUE THREAD

**Issue by sofakng** [xzyxzy/switch-patches#2]
Thanks for all of the excellent patches!

Can you please update the Mario Kart 8 Deluxe (16:10 patch) for the latest version? (3.0.1)

If not, can you provide a quick guide and maybe I can find the offset?

**Comment by xzyxzy** [comment]
https://github.com/xzyxzy/switch-patches/raw/main/MK8DX%20v3.0.1%20Mods.zip

**Comment by sofakng** [comment]
Thank you so much!!!
